REPORT ZALV_2LIST.

tables: kna1,lfa1.
select-options : cust for kna1-kunnr,
vendor for lfa1-lifnr.
data : begin of itab occurs 0,
lifnr like lfa1-lifnr,
land1 like lfa1-land1,
name1 like lfa1-name1,
end of itab.

data : begin of jtab occurs 0,
kunnr like kna1-kunnr,
land1 like kna1-land1,
name1 like kna1-name1,
end of jtab.

type-pools : slis.
data :kna1_b type slis_t_fieldcat_alv,
FIELDCATALOG1 TYPE SLIS_T_FIELDCAT_ALV , "SLIS_T_FIELDCAT_ALV
WA_FIELDCAT LIKE LINE OF FIELDCATALOG1,
FIELDCATALOG2 TYPE SLIS_T_FIELDCAT_ALV ,"WITH HEADER LINE,
layout type slis_layout_alv,
layout1 type slis_layout_alv,

layout2 type slis_layout_alv,
events_b type slis_t_event.
data : repid like sy-repid.

repid = sy-repid.
select lifnr land1 name1 from lfa1 into table itab where lifnr in vendor.

select kunnr land1 name1 from kna1 into table jtab where kunnr in cust.


*field catalofg for 1st alv
WA_FIELDCAT-FIELDNAME = 'LIFNR'.
WA_FIELDCAT-TABNAME = 'ITAB'.
WA_FIELDCAT-REF_FIELDNAME = 'LIFNR'.
WA_FIELDCAT-REF_TABNAME = 'LFA1'.
WA_FIELDCAT-SELTEXT_M = 'VENDOR'.
WA_FIELDCAT-COL_POS = 1.
WA_FIELDCAT-OUTPUTLEN = 20.
APPEND WA_FIELDCAT TO FIELDCATALOG1.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'LAND1'.
WA_FIELDCAT-TABNAME = 'ITAB'.
WA_FIELDCAT-REF_FIELDNAME = 'LAND1'.
WA_FIELDCAT-REF_TABNAME = 'LFA1'.
WA_FIELDCAT-SELTEXT_M = 'address'.
WA_FIELDCAT-COL_POS = 2.
WA_FIELDCAT-OUTPUTLEN = 20.
APPEND WA_FIELDCAT TO FIELDCATALOG1.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'NAME1'.
WA_FIELDCAT-TABNAME = 'ITAB'.
WA_FIELDCAT-REF_FIELDNAME = 'NAME1'.
WA_FIELDCAT-REF_TABNAME = 'LFA1'.
WA_FIELDCAT-SELTEXT_M = 'name'.
WA_FIELDCAT-COL_POS = 3.
WA_FIELDCAT-OUTPUTLEN = 20.
APPEND WA_FIELDCAT TO FIELDCATALOG1.
CLEAR WA_FIELDCAT.

*field catalog for 2nd alv

WA_FIELDCAT-FIELDNAME = 'KUNNR'.
WA_FIELDCAT-TABNAME = 'JTAB'.
WA_FIELDCAT-REF_FIELDNAME = 'KUNNR'.
WA_FIELDCAT-REF_TABNAME = 'KNA1'.
WA_FIELDCAT-SELTEXT_M = 'customer'.
WA_FIELDCAT-COL_POS = 1.
WA_FIELDCAT-OUTPUTLEN = 20.
APPEND WA_FIELDCAT TO FIELDCATALOG2.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'LAND1'.
WA_FIELDCAT-TABNAME = 'JTAB'.
WA_FIELDCAT-REF_FIELDNAME = 'LAND1'.
WA_FIELDCAT-REF_TABNAME = 'KNA1'.
WA_FIELDCAT-SELTEXT_M = 'address'.
WA_FIELDCAT-COL_POS = 2.
WA_FIELDCAT-OUTPUTLEN = 20.
APPEND WA_FIELDCAT TO FIELDCATALOG2.
CLEAR WA_FIELDCAT.

WA_FIELDCAT-FIELDNAME = 'NAME1'.
WA_FIELDCAT-TABNAME = 'JTAB'.
WA_FIELDCAT-REF_FIELDNAME = 'NAME1'.
WA_FIELDCAT-REF_TABNAME = 'KNA1'.
WA_FIELDCAT-SELTEXT_M = 'name'.
WA_FIELDCAT-COL_POS = 3.
WA_FIELDCAT-OUTPUTLEN = 20.
APPEND WA_FIELDCAT TO FIELDCATALOG2.
CLEAR WA_FIELDCAT.



CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_INIT'
EXPORTING
I_CALLBACK_PROGRAM = sy-cprog
.

CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_APPEND'
EXPORTING
IS_LAYOUT = LAYOUT1
IT_FIELDCAT = FIELDCATALOG1[]
I_TABNAME = 'ITAB'
IT_EVENTS = EVENTS_B[]
TABLES
T_OUTTAB = ITAB

EXCEPTIONS 
PROGRAM_ERROR = 1 
MAXIMUM_OF_APPENDS_REACHED = 2 
OTHERS = 3 
.
IF SY-SUBRC eq 0.
MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO 
WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4. 
ENDIF.


CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_APPEND'
EXPORTING
IS_LAYOUT = LAYOUT1
IT_FIELDCAT = FIELDCATALOG2[]
I_TABNAME = 'JTAB'
IT_EVENTS = EVENTS_B[]
TABLES
T_OUTTAB = JTAB
EXCEPTIONS 
PROGRAM_ERROR = 1 
MAXIMUM_OF_APPENDS_REACHED = 2 
OTHERS = 3 
.
IF SY-SUBRC EQ 0.

MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO 
WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4. 
ENDIF.


CALL FUNCTION 'REUSE_ALV_BLOCK_LIST_DISPLAY'.